[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
regex = "1.11.1"
rstest = "0.26.1"
